name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and lint on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: ['16.x', '18.x']
        os: [ubuntu-latest, windows-latest, macos-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    if: ${{ github.actor != 'dependabot[bot]' }} # Ignore dependabot triggering further builds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm install -g npm

      - name: Setup Nodejs with npm caching
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm run lint
